// Generated by AI on 07/30/2026
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import './config/database';
import { Activity, LeaderboardEntry, Team, User, Workout } from './models/octofit';

dotenv.config();

const app = express();
const PORT = 8000;
const HOST = '0.0.0.0';
const codespaceName = process.env.CODESPACE_NAME;
const baseUrl = codespaceName
  ? `https://${codespaceName}-8000.app.github.dev`
  : 'http://localhost:8000';
const allowedOrigins = codespaceName
  ? [`https://${codespaceName}-5173.app.github.dev`, 'http://localhost:5173']
  : ['http://localhost:5173'];

app.use(cors({ origin: allowedOrigins }));
app.use(express.json());

app.get('/', (_req, res) => {
  res.json({ message: 'OctoFit Tracker API', baseUrl });
});

// Modified by AI on 07/30/2026. Edit #1.
app.get('/api/users/', async (_req, res, next) => {
  try {
    const users = await User.find().lean();
    res.json(users);
  } catch (error) {
    next(error);
  }
});

// Modified by AI on 07/30/2026. Edit #1.
app.get('/api/teams/', async (_req, res, next) => {
  try {
    const teams = await Team.find().lean();
    res.json(teams);
  } catch (error) {
    next(error);
  }
});

// Modified by AI on 07/30/2026. Edit #1.
app.get('/api/activities/', async (_req, res, next) => {
  try {
    const activities = await Activity.find().lean();
    res.json(activities);
  } catch (error) {
    next(error);
  }
});

// Modified by AI on 07/30/2026. Edit #1.
app.get('/api/leaderboard/', async (_req, res, next) => {
  try {
    const leaderboard = await LeaderboardEntry.find().sort({ points: -1 }).lean();
    res.json(leaderboard);
  } catch (error) {
    next(error);
  }
});

// Modified by AI on 07/30/2026. Edit #1.
app.get('/api/workouts/', async (_req, res, next) => {
  try {
    const workouts = await Workout.find().lean();
    res.json(workouts);
  } catch (error) {
    next(error);
  }
});

// Modified by AI on 07/30/2026. Edit #1.
app.use((error: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(error);
  res.status(500).json({ message: 'Internal server error' });
});

app.listen(PORT, HOST, () => {
  console.log(`Server running on ${HOST}:${PORT}`);
  console.log(`Base URL: ${baseUrl}`);
});

export default app;