// Modified by AI on 07/30/2026. Edit #1.
import { getApiUrl } from '../api.js'
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'username', label: 'User' },
  { key: 'activityType', label: 'Activity' },
  { key: 'durationMinutes', label: 'Minutes' },
  { key: 'caloriesBurned', label: 'Calories' },
  { key: 'distanceMiles', label: 'Miles' },
]

// Modified by AI on 07/30/2026. Edit #2.
const activitiesEndpoint = import.meta.env.VITE_CODESPACE_NAME?.trim()
  ? `https://${import.meta.env.VITE_CODESPACE_NAME.trim()}-8000.app.github.dev/api/activities/`
  : getApiUrl('activities')

// Modified by AI on 07/30/2026. Edit #1.
function Activities() {
  return (
    <ResourceView
      component="activities"
      endpoint={activitiesEndpoint}
      title="Activities"
      description="Recent logged training sessions across Octofit users."
      fields={fields}
    />
  )
}

export default Activities