// Generated by AI on 07/30/2026
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'username', label: 'User' },
  { key: 'activityType', label: 'Activity' },
  { key: 'durationMinutes', label: 'Minutes' },
  { key: 'caloriesBurned', label: 'Calories' },
  { key: 'distanceMiles', label: 'Miles' },
]

// Generated by AI on 07/30/2026
function Activities() {
  return (
    <ResourceView
      component="activities"
      title="Activities"
      description="Recent logged training sessions across Octofit users."
      fields={fields}
    />
  )
}

export default Activities