// Modified by AI on 07/30/2026. Edit #1.
import { getApiUrl } from '../api.js'
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'rank', label: 'Rank' },
  { key: 'username', label: 'User' },
  { key: 'teamName', label: 'Team' },
  { key: 'points', label: 'Points' },
  { key: 'weeklyMinutes', label: 'Weekly minutes' },
]

// Modified by AI on 07/30/2026. Edit #2.
const leaderboardEndpoint = import.meta.env.VITE_CODESPACE_NAME?.trim()
  ? `https://${import.meta.env.VITE_CODESPACE_NAME.trim()}-8000.app.github.dev/api/leaderboard/`
  : getApiUrl('leaderboard')

// Modified by AI on 07/30/2026. Edit #1.
function Leaderboard() {
  return (
    <ResourceView
      component="leaderboard"
      endpoint={leaderboardEndpoint}
      title="Leaderboard"
      description="Competitive standings sorted by Octofit points."
      fields={fields}
    />
  )
}

export default Leaderboard