// Generated by AI on 07/30/2026
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'rank', label: 'Rank' },
  { key: 'username', label: 'User' },
  { key: 'teamName', label: 'Team' },
  { key: 'points', label: 'Points' },
  { key: 'weeklyMinutes', label: 'Weekly minutes' },
]

// Generated by AI on 07/30/2026
function Leaderboard() {
  return (
    <ResourceView
      component="leaderboard"
      title="Leaderboard"
      description="Competitive standings sorted by Octofit points."
      fields={fields}
    />
  )
}

export default Leaderboard