// Generated by AI on 07/30/2026
import { useEffect, useState } from 'react'
import { getApiUrl, normalizeApiItems } from '../api.js'

// Generated by AI on 07/30/2026
function getValue(item, field) {
  const value = item[field.key]

  if (Array.isArray(value)) {
    return value.join(', ')
  }

  if (field.format) {
    return field.format(value, item)
  }

  return value ?? 'Not available'
}

// Generated by AI on 07/30/2026
function ResourceView({ component, title, description, fields }) {
  const [items, setItems] = useState([])
  const [status, setStatus] = useState('loading')
  const [error, setError] = useState('')

  useEffect(() => {
    const controller = new AbortController()

    async function loadItems() {
      setStatus('loading')
      setError('')

      try {
        const response = await fetch(getApiUrl(component), { signal: controller.signal })

        if (!response.ok) {
          throw new Error(`Request failed with ${response.status}`)
        }

        const payload = await response.json()
        setItems(normalizeApiItems(payload))
        setStatus('ready')
      } catch (requestError) {
        if (requestError.name !== 'AbortError') {
          setError(requestError.message)
          setStatus('error')
        }
      }
    }

    loadItems()

    return () => controller.abort()
  }, [component])

  return (
    <section className="resource-view">
      <div className="resource-heading">
        <div>
          <p className="eyebrow">/api/{component}/</p>
          <h2>{title}</h2>
          <p>{description}</p>
        </div>
        <span className="record-count">{items.length} records</span>
      </div>

      {status === 'loading' && <p className="notice">Loading {title.toLowerCase()}...</p>}
      {status === 'error' && <p className="notice error">Unable to load data: {error}</p>}
      {status === 'ready' && items.length === 0 && <p className="notice">No records returned yet.</p>}

      {status === 'ready' && items.length > 0 && (
        <div className="table-wrap">
          <table className="table align-middle mb-0">
            <thead>
              <tr>
                {fields.map((field) => (
                  <th key={field.key} scope="col">
                    {field.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {items.map((item, index) => (
                <tr key={item._id ?? item.id ?? `${component}-${index}`}>
                  {fields.map((field) => (
                    <td key={field.key}>{getValue(item, field)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  )
}

export default ResourceView