// Modified by AI on 07/30/2026. Edit #1.
import { getApiUrl } from '../api.js'
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'name', label: 'Team' },
  { key: 'city', label: 'City' },
  { key: 'coach', label: 'Coach' },
  { key: 'mascot', label: 'Mascot' },
  { key: 'memberCount', label: 'Members' },
]

// Modified by AI on 07/30/2026. Edit #2.
const teamsEndpoint = import.meta.env.VITE_CODESPACE_NAME?.trim()
  ? `https://${import.meta.env.VITE_CODESPACE_NAME.trim()}-8000.app.github.dev/api/teams/`
  : getApiUrl('teams')

// Modified by AI on 07/30/2026. Edit #1.
function Teams() {
  return (
    <ResourceView
      component="teams"
      endpoint={teamsEndpoint}
      title="Teams"
      description="Team rosters and coaching details for Octofit groups."
      fields={fields}
    />
  )
}

export default Teams