// Generated by AI on 07/30/2026
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'name', label: 'Team' },
  { key: 'city', label: 'City' },
  { key: 'coach', label: 'Coach' },
  { key: 'mascot', label: 'Mascot' },
  { key: 'memberCount', label: 'Members' },
]

// Generated by AI on 07/30/2026
function Teams() {
  return (
    <ResourceView
      component="teams"
      title="Teams"
      description="Team rosters and coaching details for Octofit groups."
      fields={fields}
    />
  )
}

export default Teams