// Generated by AI on 07/30/2026
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'displayName', label: 'Name' },
  { key: 'username', label: 'Username' },
  { key: 'email', label: 'Email' },
  { key: 'teamName', label: 'Team' },
  { key: 'fitnessGoal', label: 'Goal' },
]

// Generated by AI on 07/30/2026
function Users() {
  return (
    <ResourceView
      component="users"
      title="Users"
      description="Athlete profiles, goals, and team assignments."
      fields={fields}
    />
  )
}

export default Users