// Modified by AI on 07/30/2026. Edit #1.
import { getApiUrl } from '../api.js'
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'displayName', label: 'Name' },
  { key: 'username', label: 'Username' },
  { key: 'email', label: 'Email' },
  { key: 'teamName', label: 'Team' },
  { key: 'fitnessGoal', label: 'Goal' },
]

// Modified by AI on 07/30/2026. Edit #2.
const usersEndpoint = import.meta.env.VITE_CODESPACE_NAME?.trim()
  ? `https://${import.meta.env.VITE_CODESPACE_NAME.trim()}-8000.app.github.dev/api/users/`
  : getApiUrl('users')

// Modified by AI on 07/30/2026. Edit #1.
function Users() {
  return (
    <ResourceView
      component="users"
      endpoint={usersEndpoint}
      title="Users"
      description="Athlete profiles, goals, and team assignments."
      fields={fields}
    />
  )
}

export default Users