// Modified by AI on 07/30/2026. Edit #1.
import { getApiUrl } from '../api.js'
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'title', label: 'Workout' },
  { key: 'focusArea', label: 'Focus' },
  { key: 'difficulty', label: 'Difficulty' },
  { key: 'durationMinutes', label: 'Minutes' },
  { key: 'suggestedForGoal', label: 'Suggested goal' },
  { key: 'exercises', label: 'Exercises' },
]

// Modified by AI on 07/30/2026. Edit #2.
const workoutsEndpoint = import.meta.env.VITE_CODESPACE_NAME?.trim()
  ? `https://${import.meta.env.VITE_CODESPACE_NAME.trim()}-8000.app.github.dev/api/workouts/`
  : getApiUrl('workouts')

// Modified by AI on 07/30/2026. Edit #1.
function Workouts() {
  return (
    <ResourceView
      component="workouts"
      endpoint={workoutsEndpoint}
      title="Workouts"
      description="Personalized workout suggestions grouped by goal and intensity."
      fields={fields}
    />
  )
}

export default Workouts