// Generated by AI on 07/30/2026
import ResourceView from './ResourceView.jsx'

// Generated by AI on 07/30/2026
const fields = [
  { key: 'title', label: 'Workout' },
  { key: 'focusArea', label: 'Focus' },
  { key: 'difficulty', label: 'Difficulty' },
  { key: 'durationMinutes', label: 'Minutes' },
  { key: 'suggestedForGoal', label: 'Suggested goal' },
  { key: 'exercises', label: 'Exercises' },
]

// Generated by AI on 07/30/2026
function Workouts() {
  return (
    <ResourceView
      component="workouts"
      title="Workouts"
      description="Personalized workout suggestions grouped by goal and intensity."
      fields={fields}
    />
  )
}

export default Workouts