// Modified by AI on 07/30/2026. Edit #1.
const codespaceName = import.meta.env.VITE_CODESPACE_NAME?.trim()

// Modified by AI on 07/30/2026. Edit #1.
function getCurrentHost() {
  return typeof window === 'undefined' ? '' : window.location.hostname
}

// Modified by AI on 07/30/2026. Edit #2.
function getCodespaceNameFromHost() {
  return getCurrentHost().replace(/-5173\.app\.github\.dev$/, '')
}

// Modified by AI on 07/30/2026. Edit #2.
function getApiBaseUrl() {
  const currentHost = getCurrentHost()
  const activeCodespaceName = codespaceName || getCodespaceNameFromHost()

  if (activeCodespaceName && activeCodespaceName !== currentHost) {
    return `https://${activeCodespaceName}-8000.app.github.dev/api`
  }

  return 'http://localhost:8000/api'
}

// Modified by AI on 07/30/2026. Edit #1.
export const apiBaseUrl = getApiBaseUrl()

// Modified by AI on 07/30/2026. Edit #1.
export function getApiUrl(component) {
  return `${apiBaseUrl}/${component}/`
}

// Generated by AI on 07/30/2026
export function normalizeApiItems(payload) {
  if (Array.isArray(payload)) {
    return payload
  }

  if (!payload || typeof payload !== 'object') {
    return []
  }

  const paginatedKeys = ['results', 'items', 'data', 'docs', 'records']
  const paginatedItems = paginatedKeys.map((key) => payload[key]).find(Array.isArray)

  return paginatedItems ?? []
}