// Generated by AI on 07/30/2026
const codespaceName = import.meta.env.VITE_CODESPACE_NAME?.trim()

// Generated by AI on 07/30/2026
export const apiBaseUrl = codespaceName
  ? `https://${codespaceName}-8000.app.github.dev/api`
  : 'http://localhost:8000/api'

// Generated by AI on 07/30/2026
export function getApiUrl(component) {
  return `${apiBaseUrl}/${component}/`
}

// Generated by AI on 07/30/2026
export function normalizeApiItems(payload) {
  if (Array.isArray(payload)) {
    return payload
  }

  if (!payload || typeof payload !== 'object') {
    return []
  }

  const paginatedKeys = ['results', 'items', 'data', 'docs', 'records']
  const paginatedItems = paginatedKeys.map((key) => payload[key]).find(Array.isArray)

  return paginatedItems ?? []
}