// Generated by AI on 07/30/2026
import { Schema, model, models } from 'mongoose';

// Modified by AI on 07/30/2026. Edit #1.
const userSchema = new Schema(
  {
    username: { type: String, required: true, unique: true, trim: true },
    email: { type: String, required: true, unique: true, trim: true },
    displayName: { type: String, required: true, trim: true },
    age: { type: Number, required: true, min: 13 },
    fitnessGoal: { type: String, required: true, trim: true },
    teamName: { type: String, required: true, trim: true },
    joinedAt: { type: Date, default: Date.now },
  },
  { collection: 'users' },
);

// Modified by AI on 07/30/2026. Edit #1.
const teamSchema = new Schema(
  {
    name: { type: String, required: true, unique: true, trim: true },
    mascot: { type: String, required: true, trim: true },
    city: { type: String, required: true, trim: true },
    coach: { type: String, required: true, trim: true },
    memberCount: { type: Number, required: true, min: 1 },
  },
  { collection: 'teams' },
);

// Modified by AI on 07/30/2026. Edit #1.
const activitySchema = new Schema(
  {
    username: { type: String, required: true, trim: true },
    activityType: { type: String, required: true, trim: true },
    durationMinutes: { type: Number, required: true, min: 1 },
    caloriesBurned: { type: Number, required: true, min: 1 },
    distanceMiles: { type: Number, min: 0 },
    completedAt: { type: Date, required: true },
  },
  { collection: 'activities' },
);

// Modified by AI on 07/30/2026. Edit #1.
const leaderboardEntrySchema = new Schema(
  {
    username: { type: String, required: true, unique: true, trim: true },
    teamName: { type: String, required: true, trim: true },
    points: { type: Number, required: true, min: 0 },
    rank: { type: Number, required: true, min: 1 },
    weeklyMinutes: { type: Number, required: true, min: 0 },
  },
  { collection: 'leaderboard' },
);

// Modified by AI on 07/30/2026. Edit #1.
const workoutSchema = new Schema(
  {
    title: { type: String, required: true, trim: true },
    focusArea: { type: String, required: true, trim: true },
    difficulty: { type: String, required: true, enum: ['Beginner', 'Intermediate', 'Advanced'] },
    durationMinutes: { type: Number, required: true, min: 1 },
    suggestedForGoal: { type: String, required: true, trim: true },
    exercises: [{ type: String, required: true, trim: true }],
  },
  { collection: 'workouts' },
);

export const User = models.User || model('User', userSchema);
export const Team = models.Team || model('Team', teamSchema);
export const Activity = models.Activity || model('Activity', activitySchema);
export const LeaderboardEntry = models.LeaderboardEntry || model('LeaderboardEntry', leaderboardEntrySchema);
export const Workout = models.Workout || model('Workout', workoutSchema);